apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend

  minReplicas: 2
  maxReplicas: 15            # Backend scales more

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # Aggressive CPU scaling

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60   # Scale if memory > 60%
